# iNZight Code History

## This script was automatically generated by iNZight v4.2.0

## -------------------------------------------------------------------------- ##

## This script assumes you have the following packages installed.
## Uncomment the following lines if you don't:

# install.packages(c('iNZightPlots',
#                    'magrittr'), 
#     repos = c('https://r.docker.stat.auckland.ac.nz',
#               'https://cran.rstudio.com'))

## -------------------------------------------------------------------------- ##

library(magrittr)  # enables the pipe (%>%) operator
library(iNZightPlots)

Gapminder <- readr::read_csv("Gapminder.csv",
    comment = "#",
    col_types = readr::cols(),
    locale = readr::locale(
        encoding = "UTF-8",
        decimal_mark = ".",
        grouping_mark = ","
    ),
    lazy = FALSE
) %>%
    dplyr::mutate_at(
        c(
            "Country",
            "Region-Geo",
            "Continent",
            "Region",
            "Year_cat"
        ),
        as.factor
    ) %>%
    dplyr::rename(Region.Geo = "Region-Geo")

Gapminder.filtered <- Gapminder %>%
    dplyr::filter(Year_cat %in% c(
        "[1960]",
        "[1964]",
        "[1968]",
        "[1972]",
        "[1976]",
        "[1980]",
        "[1984]",
        "[1988]",
        "[1992]",
        "[1996]",
        "[2000]",
        "[2004]",
        "[2008]"
    )) %>%
    droplevels()

inzplot(Infantmortality ~ GDPpercapita | Year_cat,
    colby = Region,
    sizeby = Populationtotal,
    data = Gapminder.filtered,
    xlab = "GDP per capita (log scale)",
    ylab = "Infant mortality",
    col.fun = "contrast",
    cex = 0.7,
    alpha = 0.4,
    transform = list(x = "log10"),
    main = "Infant mortality by GDP over time"
)

Gapminder.filtered.separated <- data %>% tidyr::separate(
    col = "Region.Geo",
    into = c(
        "main_region",
        "part_region"
    ),
    sep = "_",
    extra = "merge"
)

## Load example data set
data(apiclus1, package = 'survey')

## -------------------------------------------------------------------------- ## 
## Exploring the 'apiclus1_ex' dataset

apiclus1_ex <- apiclus1

## create survey design object 
apiclus1_ex.svy <- survey::svydesign(ids = ~dnum, fpc = ~fpc, nest = FALSE, weights = ~pw, 
    data = apiclus1_ex)

## Load example data set
data(visitorsQ, package = 'iNZightTS')

## -------------------------------------------------------------------------- ## 
## Exploring the 'visitorsQ_ex' dataset

visitorsQ_ex <- visitorsQ

